# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Shambles
description: > # this means to ignore newlines until "baseurl:"
 The Shambles are York's premier improv troupe, we do a variety of songs, scenes and games based completley on your own suggestions!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

defaults:
  - scope:
      path: "img"
    values:
      image: true

author: Qumarth Jash
author_website: http://qumarth.uk
designer: Ed Williams
designer_website: http://twitter.com/Edface
photographer: Harry Elletson
photographer_website: http://hlhelletson.wixsite.com/portfolio

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

prose:
  siteurl: 'http://shamblesimprov.co.uk'
  media: 'img'
  ignore: ['_config.yml',
           '_sass',
           'CNAME',
           '.gitignore',
           'css',
           'font-awesome',
           'bootstrap']
